url: https://SmashVR.github.io
baseurl: /SmashVR.github.io/

# Site settings
title: USC Games
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sukriti Sharma
  pic: 1
  email: sukritis@usc.edu
  social:
    - title: github
      url: https://github.com/SukritiSharma
    - title: linkedin
      url: https://www.linkedin.com/in/sukriti-sharma-20/
    

- name: Saurabh Thakur
  pic: 2
  email: scthakur@usc.edu
  social:
    - title: github
      url: https://github.com/thakursc1
    - title: linkedin
      url: https://www.linkedin.com/in/thakursc1/

- name: Dixita Patel
  pic: 3
  email: dixitapa@usc.edu
  social:
    - title: github
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/dixitapatel42/

- name: Ishita Patel
  pic: 4
  email: ishitanp@usc.edu 
  social:
    - title: github
      url: https://github.com/ishu63
    - title: linkedin
      url: https://www.linkedin.com/in/ishitanpatel/

- name: Keerthi Maganti
  pic: 5
  email: keerthim@usc.edu 
  social:
    - title: github
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/keerthi-maganti/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: ..


# Build settings
markdown: kramdown
permalink: pretty
